Name:           ros-hydro-pr2-navigation-config
Version:        0.1.26
Release:        0%{?dist}
Summary:        ROS pr2_navigation_config package

Group:          Development/Libraries
License:        BSD
URL:            http://pr.willowgarage.com/wiki
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-hydro-move-base
BuildRequires:  ros-hydro-catkin
BuildRequires:  ros-hydro-move-base

%description
This package holds common configuration files for running the

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/hydro/setup.sh" ]; then . "/opt/ros/hydro/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/hydro" \
        -DCMAKE_PREFIX_PATH="/opt/ros/hydro" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/hydro/setup.sh" ]; then . "/opt/ros/hydro/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/hydro

%changelog
* Tue Jun 16 2015 Devon Ash <dash@clearpathrobotics.com> - 0.1.26-0
- Autogenerated by Bloom

* Wed Oct 15 2014 Devon Ash <dash@clearpathrobotics.com> - 0.1.23-0
- Autogenerated by Bloom

* Mon Sep 08 2014 Maintained by Eitan Marder-Eppstein <eitan@willowgarage.com> - 0.1.22-0
- Autogenerated by Bloom

